# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte II e Matplotlib - Avaliação</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)
Qual dos códigos abaixo corretamente utiliza broadcasting para construir uma matriz cujas **colunas** são todas formadas pelos elementos [0,1,2,3]?
```python
A = np.zeros((4,4))
v = np.arange(4)
```

a)
```python
A[:] = v[:,np.newaxis]
```
b) 
```python
A[:] = v.reshape(4,1)
```
c)
```python
A[:] = v
A = A.T
```
d) Todas as alternativas estão corretas

In [7]:
A = np.zeros((4,4))
v = np.arange(4)

print(f'A:\n{A}\n')
print(f'v:\n{v}\n')

A[:] = v
A = A.T
print(f'A:\n{A}\n')

A:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

v:
[0 1 2 3]

A:
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]



### Exercício 2)
Qual das alternativas corretamente explica como o array `W` está sendo calculando no código abaixo?
```python
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
```

a) O array `W` possui 10 elementos como resultado da soma dos arrays `u` e `v`, onde `u` é complementado com zeros durante o broadcasting.<br>
b) O array `W` é uma matriz com 10 linhas e 7 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 colunas e do array `u` em 10 linhas.<br>
c) O array `W` é uma matriz com 7 linhas e 10 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 linhas e o array `u` em 10 linhas.<br>
d) O array `W` possui 7 elementos como resultado da soma dos arrays `u` e `v`, onde os três útlimos elementos de `v` são descartados no broadcasting.

In [13]:
np.random.seed(2)

u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

print(f'u:\n{u}\n')
print(f'v:\n{v}\n')

W = v + u

print(f'W:\n{W}\n')

u:
[ 8 15 13  8 22 11 18]

v:
[[11]
 [ 8]
 [ 7]
 [ 2]
 [17]
 [11]
 [21]
 [15]
 [26]
 [20]]

W:
[[19 26 24 19 33 22 29]
 [16 23 21 16 30 19 26]
 [15 22 20 15 29 18 25]
 [10 17 15 10 24 13 20]
 [25 32 30 25 39 28 35]
 [19 26 24 19 33 22 29]
 [29 36 34 29 43 32 39]
 [23 30 28 23 37 26 33]
 [34 41 39 34 48 37 44]
 [28 35 33 28 42 31 38]]



### Exercício 3)
Considere a matriz abaixo. Utilizando redução, encontre o **índice da linha** que possui a maior soma dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```
a) linha 6<br>
b) linha 0<br>
c) linha 8<br>
d) linha 9

In [18]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

print(f'A:\n{A}\n')
print(f'A.shape:\n{A.shape}\n')
A_rowsum = np.sum(A,axis=1)
print(f'A_rowsum:\n{A_rowsum}\n')
A_rowsum_maxarg = np.argmax(A_rowsum)
print(f'A_rowsum_maxarg:\n{A_rowsum_maxarg}\n')

A:
[[5 2 3 6 1 5 7 7 8 9]
 [8 8 3 5 0 1 4 8 3 7]
 [8 0 0 4 2 0 2 6 0 3]
 [5 0 0 4 4 3 5 8 0 0]
 [2 4 2 5 3 4 9 8 0 0]
 [6 7 4 8 5 1 3 5 4 1]
 [6 8 0 5 2 9 3 6 1 6]
 [5 5 2 9 0 5 5 8 2 4]
 [8 8 1 8 4 1 8 9 7 6]
 [5 6 0 9 0 4 9 0 2 0]]

A.shape:
(10, 10)

A_rowsum:
[53 47 25 29 37 44 46 45 60 35]

A_rowsum_maxarg:
8



### Exercício 4) 
Considerando a matriz `A` do exercício anterior, qual o **índice da coluna** que possui a menor média de valores?

a) coluna 2<br>
b) coluna 0<br>
c) coluna 8<br>
d) coluna 9

In [20]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

print(f'A:\n{A}\n')
print(f'A.shape:\n{A.shape}\n')
A_colmean = np.mean(A,axis=0)
print(f'A_colmean:\n{A_colmean}\n')
A_colmean_minarg = np.argmin(A_colmean)
print(f'A_colmean_minarg:\n{A_colmean_minarg}\n')

A:
[[5 2 3 6 1 5 7 7 8 9]
 [8 8 3 5 0 1 4 8 3 7]
 [8 0 0 4 2 0 2 6 0 3]
 [5 0 0 4 4 3 5 8 0 0]
 [2 4 2 5 3 4 9 8 0 0]
 [6 7 4 8 5 1 3 5 4 1]
 [6 8 0 5 2 9 3 6 1 6]
 [5 5 2 9 0 5 5 8 2 4]
 [8 8 1 8 4 1 8 9 7 6]
 [5 6 0 9 0 4 9 0 2 0]]

A.shape:
(10, 10)

A_colmean:
[5.8 4.8 1.5 6.3 2.1 3.3 5.5 6.5 2.7 3.6]

A_colmean_minarg:
2



### Exercício 5)
Suponha que a variável `A` no código abaixo é uma matriz com $n$ linhas e $m$ colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
```
a) Substituindo o maior valor de cada coluna por -1<br>
b) Substituindo o maior valor de cada linha por -1<br>
c) Substituindo o menor valor de cada linha por -1<br>
d) Substituindo o menor valor de cada coluna por -1

In [25]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

A = A*10
print(f'A:\n{A}\n')
Aargs = np.argsort(A)
print(f'Aargs:\n{Aargs}\n')
A[np.arange(A.shape[0]),Aargs[:,-1]] = -1
print(f'A:\n{A}\n')

A:
[[50 20 30 60 10 50 70 70 80 90]
 [80 80 30 50  0 10 40 80 30 70]
 [80  0  0 40 20  0 20 60  0 30]
 [50  0  0 40 40 30 50 80  0  0]
 [20 40 20 50 30 40 90 80  0  0]
 [60 70 40 80 50 10 30 50 40 10]
 [60 80  0 50 20 90 30 60 10 60]
 [50 50 20 90  0 50 50 80 20 40]
 [80 80 10 80 40 10 80 90 70 60]
 [50 60  0 90  0 40 90  0 20  0]]

Aargs:
[[4 1 2 0 5 3 6 7 8 9]
 [4 5 2 8 6 3 9 0 1 7]
 [1 2 5 8 4 6 9 3 7 0]
 [1 2 8 9 5 3 4 0 6 7]
 [8 9 0 2 4 1 5 3 7 6]
 [5 9 6 2 8 4 7 0 1 3]
 [2 8 4 6 3 0 7 9 1 5]
 [4 2 8 9 0 1 5 6 7 3]
 [2 5 4 9 8 0 1 3 6 7]
 [2 4 7 9 8 5 0 1 3 6]]

A:
[[50 20 30 60 10 50 70 70 80 -1]
 [80 80 30 50  0 10 40 -1 30 70]
 [-1  0  0 40 20  0 20 60  0 30]
 [50  0  0 40 40 30 50 -1  0  0]
 [20 40 20 50 30 40 -1 80  0  0]
 [60 70 40 -1 50 10 30 50 40 10]
 [60 80  0 50 20 -1 30 60 10 60]
 [50 50 20 -1  0 50 50 80 20 40]
 [80 80 10 80 40 10 80 -1 70 60]
 [50 60  0 90  0 40 -1  0 20  0]]

